django_teams/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views import static

from django.contrib import admin
admin.autodiscover()

from django_teams.views import *

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    # TemplateView + Login
    #url(r'^$', login_required(TemplateView.as_view(template_name="home.html")), {}, 'home'),
    url(r'^teams/$', TeamListView.as_view(), name='team-list'),
    url(r'^my-teams/$', login_required(UserTeamListView.as_view()), name='user-team-list'),
    url(r'^teams/create$', login_required(TeamCreateView.as_view()), name='team-create'),
    url(r'^teams/(?P<team_pk>\d+)/invite$', login_required(TeamStatusCreateView.as_view()), name='teamstatus-create'),
    url(r'^teams/(?P<pk>\d+)/$', TeamDetailView.as_view(), name='team-detail'),
    url(r'^teams/(?P<pk>\d+)/edit$', TeamEditView.as_view(), name='team-edit'),
    url(r'^teams/(?P<pk>\d+)/info/edit$', TeamInfoEditView.as_view(), name='team-info-edit'),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static.serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
   ]

django_teams/models.py
# This is where the models go!
import types
import inspect
import sys
from django.db import models
from django.db.models.query import QuerySet
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ObjectDoesNotExist

# Using the user: user = models.ForeignKey(settings.AUTH_USER_MODEL)
CurrentUser = None
CurrentTeam = None

class Team(models.Model):
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, through='django_teams.TeamStatus', related_name='team_member')
    name = models.CharField(max_length=255)
    private = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('team-detail', kwargs={'pk':self.pk})

    def __unicode__(self):
        return self.name

    def add_user(self, user, team_role=1):
        TeamStatus(user=user, team=self, role=team_role).save()

    def owners(self):
        return self.users.filter(teamstatus__role=20)

    def members(self):
        return self.users.filter(teamstatus__role=10)

    def requests(self):
        return TeamStatus.objects.filter(team=self, role=1)

    def owned_objects(self, model):
        # Maybe not the best way
        contenttype = ContentType.objects.get_for_model(model)
        ret = []
        
        # I'm pretty sure there's a django one liner for this but I don't feel like looking right now
        # Someone might want to do that in the future
        for ownership in Ownership.objects.filter(team=self, content_type=contenttype):
            ret += [ownership.content_object]
            
        return ret

    def unapproved_objects(self):
        return Ownership.objects.filter(team=self, approved=False)
      
    def approved_objects(self):
        return Ownership.objects.filter(team=self, approved=True)
      
    def approved_objects_of_model(self, model):
        # Maybe not the best way
        contenttype = ContentType.objects.get_for_model(model)
        ret = []
        
        # I'm pretty sure there's a django one liner for this but I don't feel like looking right now
        # Someone might want to do that in the future
        for ownership in Ownership.objects.filter(team=self, content_type=contenttype, approved=True):
            ret += [ownership.content_object]
            
        return ret          

    def owned_object_types(self):
        ret = []
        for ownership in Ownership.objects.filter(team=self):
            if ownership.content_type.model_class() not in ret:
                ret += [ownership.content_type.model_class()]
        return ret

    def member_count(self):
        return self.users.all().count()

    def get_user_status(self, user):
        s = TeamStatus.objects.filter(user=user, team=self)
        if len(s) >= 1:
            return s[0]
        return None

    def approve_user(self, user):
        ts = TeamStatus.objects.get(user=user, team=self)
        if ts.role == 1:
            ts.role = 10
            ts.save()

    @staticmethod
    def get_current_team():
        if CurrentTeam != None:
            return CurrentTeam
        return None


class TeamStatus(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    team = models.ForeignKey('django_teams.Team', on_delete=models.CASCADE)
    comment = models.CharField(max_length=255, default='')

    TEAM_ROLES = (
        (1, 'Requesting Access'),
        (10, 'Team Member'),
        (20, 'Team Leader'),
    )

    role = models.IntegerField(choices=TEAM_ROLES)

    def approve(self):
      self.role = 10
      self.save()
    
    def __unicode__(self):
        return "%s requesting to join %s" % (self.user.__unicode__(), self.team.__unicode__())

class Ownership(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    
    approved = models.BooleanField(default=False)


    team = models.ForeignKey('django_teams.Team', on_delete=models.CASCADE)
    
    @staticmethod
    def check_permission(item):
        content_type = ContentType.objects.get_for_model(item)
        res = Ownership.objects.filter(team=Team.get_current_team(), content_type=content_type, object_id=item.id)

        return len(res) > 0

    @staticmethod
    def grant_ownership(team, item):
        content_type = ContentType.objects.get_for_model(item)

        res = Ownership.objects.get_or_create(team=team, content_type=content_type, object_id=item.id)
        if res[1]:
            res[0].save()

django_teams/forms.py
from django.forms import ModelForm, widgets
from django import forms
from django.utils.html import format_html
from itertools import chain
from django_teams.models import Team, TeamStatus
from django.utils.safestring import mark_safe
from django.utils.encoding import force_text
from django.template import Context, Template, loader as TemplateLoader

class TeamCreateForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'description', 'private']

class TeamEditForm(ModelForm):
    """This form is very complicated;
    it consists of a hash containing :
        An array of pending requests
        An array of team leaders
        An array of team members
    The form should allow the team leaders to perform the following
    actions on any number of elements from each array, at the same time:
        Pending requests;
            approve
            deny
        Team Leaders
            Demote
            Remove
        Team Members
            Promote
            Remove
    """

    class Meta:
        model = Team
        fields = ['users', 'name', 'description', 'private']

class TeamStatusCreateForm(ModelForm):

    comment = forms.CharField(required=False)

    class Meta:
        model = TeamStatus
        fields = ['comment']

def action_formset(qset, actions, link=False):
    """A form factory which returns a form which allows the user to pick a specific action to
    perform on a chosen subset of items from a queryset.
    """
    class _ActionForm(forms.Form):
        queryset = qset
        items = forms.ModelMultipleChoiceField(queryset = qset, required=False)
        action = forms.ChoiceField(choices = zip(actions, actions), required=False)

    return _ActionForm

django_teams/views.py
from django.core.exceptions import PermissionDenied
# This is where your views go :)
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Count, F
from django_teams.models import Team, TeamStatus, Ownership
from django_teams.forms import (TeamEditForm,
                                TeamStatusCreateForm,
                                action_formset)
from django.db.models import Case, When
from django.db import models
from django.contrib.contenttypes.models import ContentType


def loadGenericKeyRelations(queryset):
    distinct_contents = queryset.values_list('content_type', flat=True).distinct()
    object_items = []
    for object in distinct_contents:
        content_type = ContentType.objects.get(id=object).model_class()
        set = queryset.filter(content_type=object).values()
        objects = content_type.objects.filter(pk__in=[object['object_id'] for object in set])
        for relation in content_type._meta.get_fields():
            if relation.get_internal_type() is 'ForeignKey':
                objects.select_related(relation.name)
        object_items.append(objects.all())
    return object_items


class TeamListView(ListView):
    model = Team

    def render_to_response(self, context, **response_kwargs):
        queryset = Team.objects.all().annotate(member_count=Count('users'))
        queryset = queryset.annotate(owner=Case(When(teamstatus__role=20, then=F('users__username')), default=None))
        if not self.request.user.is_anonymous():
            queryset = queryset.annotate(role=Case(When(teamstatus__user=self.request.user,
                                         then=F('teamstatus__role')), default=0, outputfield=models.IntegerField()))
            queryset = queryset.order_by('-role', 'name')
        else:
            queryset = queryset.order_by('-id')
        team_names = []
        team_list = []
        # combine teams with the same name
        for q in queryset:
            if q.name not in team_names:
                team_names.append(q.name)
                tmp = {'name': q.name, 'id': q.id, 'pk': q.pk, 'description': q.description,
                       'member_count': q.member_count, 'owner': q.owner}
                try:
                    tmp['role'] = q.role
                except Exception:
                    tmp['role'] = None
                team_list.append(tmp)
            else:
                t = team_list[team_names.index(q.name)]
                t['member_count'] += q.member_count
                if q.owner is not None:
                    t['owner'] = q.owner
        return super(TeamListView, self).render_to_response({'list': team_list}, **response_kwargs)


class UserTeamListView(ListView):
    template_name = 'django_teams/user_team_list.html'

    def get_queryset(self):
        statuses = TeamStatus.objects.select_related('user').filter(user=self.request.user,
                                                                    role=20).values_list('team', flat=True)
        return statuses


class TeamCreateView(CreateView):
    model = Team
    template_name = 'django_teams/team_create.html'
    fields = ['name', 'description', 'private']

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super(TeamCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        ret = super(TeamCreateView, self).form_valid(form)
        self.object.add_user(self.request.user, team_role=20)
        return ret


class TeamDetailView(DetailView):
    model = Team

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super(TeamDetailView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        object = super(TeamDetailView, self).get_object(queryset)
        if object.private and self.request.user not in object.users.filter(teamstatus__role__gte=10):
            raise PermissionDenied()
        return object

    def render_to_response(self, context, **response_kwargs):
        team = self.object
        # context['owner'] = team.users.filter(teamstatus__role=20)
        # context['members'] = team.users.filter(teamstatus__role=10)
        context['owners'] = []
        context['members'] = []
        statuses = TeamStatus.objects.select_related('user', 'team').filter(team=team)
        for s in statuses:
            if s.role == 10:
                context['members'].append(s.user)
            elif s.role == 20:
                context['owners'].append(s.user)
        owned = Ownership.objects.filter(team=team, approved=True)
        context['approved_objects_types'] = loadGenericKeyRelations(owned)
        return super(TeamDetailView, self).render_to_response(context, **response_kwargs)


class TeamInfoEditView(UpdateView):
    model = Team
    fields = ['name', 'description', 'private']
    template_name = 'django_teams/teaminfo_form.html'

    def get_object(self, queryset=None):
        object = super(TeamInfoEditView, self).get_object(queryset)
        if self.request.user not in object.users.filter(teamstatus__role__gte=20):
            raise PermissionDenied()
        return object


class TeamEditView(UpdateView):
    model = Team
    form_class = TeamEditForm

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super(TeamEditView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        object = super(TeamEditView, self).get_object(queryset)

        # User must be admin of the object to get into this view
        if self.request.user not in object.users.filter(teamstatus__role__gte=20):
            raise PermissionDenied()
        return object

    def get_form_class(self):
        # get forms for team leaders, team members, team requests
        ret = []
        users = self.object.users
        ret += [action_formset(prefix_name='teachers', qset=users.filter(teamstatus__role=20),
                               actions=('---', 'Demote', 'Remove'))]
        ret += [action_formset(prefix_name='students', qset=users.filter(teamstatus__role=10),
                               actions=('---', 'Promote', 'Remove'))]
        ret += [action_formset(prefix_name='member-requests', qset=users.filter(teamstatus__role=1),
                               actions=('---', 'Approve', 'Reject'))]
        owned_objects = Ownership.objects.filter(team=self.object)
        approved = loadGenericKeyRelations(owned_objects.filter(approved=True))
        for set in approved:
            if set:
                prefix_name = 'approved-' + str(set.model.__name__)
                ret += [action_formset(prefix_name=prefix_name, qset=set, actions=('---', 'Remove'), link=True)]
        pending_approval = loadGenericKeyRelations(owned_objects.filter(approved=False))
        for set in pending_approval:
            if set:
                prefix_name = str(set.model.__name__) + 's-pending-approval'
                ret += [action_formset(prefix_name=prefix_name, qset=set,
                                       actions=('---', 'Approve', 'Remove'), link=True)]
        return ret

    def get_form(self, form_class=TeamEditForm):
        kwargs = self.get_form_kwargs()
        form_class = self.get_form_class()
        if 'data' in kwargs:
            ret = [form_class[num](kwargs['data'],
                                   prefix=form_class[num].name) for num in range(len(form_class))]
        else:
            ret = [form_class[num](prefix=form_class[num].name) for num in range(len(form_class))]

        return ret

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        self.object = get_object_or_404(Team, pk=kwargs['pk'])
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        for f in form:
            if not f.is_valid():
                return self.form_invalid(form)

        # Go through each form and perform the action
        # Owners
        owner_action = form[0].cleaned_data['action']
        owner_items = form[0].cleaned_data['items']
        statuses = TeamStatus.objects.filter(team=self.object, user__in=[object for object in owner_items])
        if owner_action == 'Demote':
            for status in statuses:
                status.role = 10
                status.save()
        if owner_action == 'Remove':
            for status in statuses:
                status.delete()

        # Members
        member_action = form[1].cleaned_data['action']
        member_items = form[1].cleaned_data['items']
        statuses = TeamStatus.objects.filter(team=self.object, user__in=[object for object in member_items])
        if member_action == 'Promote':
            for status in statuses:
                status.role = 20
                status.save()
        if member_action == 'Remove':
            for status in statuses:
                status.delete()

        # Member Requests
        request_action = form[2].cleaned_data['action']
        request_items = form[2].cleaned_data['items']
        statuses = TeamStatus.objects.filter(team=self.object, user__in=[object for object in request_items])
        if request_action == 'Approve':
            for status in statuses:
                status.role = 10
                status.save()
        if request_action == 'Revoke':
            for status in statuses:
                status.delete()

        for num in range(3, len(form)):
            current_action = form[num].cleaned_data['action']
            current_items = form[num].cleaned_data['items']

django_teams/templates/django_teams/_table.html
{% load teams %}
<tr>
  <td>
    <a href="{% url 'team-detail' pk=team.id %}">{{ team.name }}</a>
    {% if not user.is_anonymous %}
        {% if team.role == 20 %}
            (<a href="{% url 'team-edit' pk=team.pk %}">Admin</a>)
        {% endif %}
    {% endif %}
  </td>
  <td>{% if team.description %}{{ team.description|truncatewords:15 }}{% endif %}</td>
  <td>{{ team.owner }}</td>
  <td>{{ team.member_count }}</td>
  <td>
  {% if not user.is_anonymous %}
              {% if team.role == 0 %}
                  <a href="{% url 'teamstatus-create' team_pk=team.pk %}">Join</a>
              {% elif team.role == 1 %}
                  Pending approval
              {% elif team.role == 10 %}
                  Member
              {% elif team.role == 20 %}
                  Teacher (<a href="{% url 'team-edit' pk=team.pk %}">Admin</a>)
              {% endif %}
      {% else %}
          You're not logged in!
      {% endif %}
  </td>
</tr>

django_teams/templates/django_teams/team_create.html
{% extends 'base.html' %}

{% block page-header %}
<h1>Create classroom</h1>
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" action="{% url 'team-create' %}" enctype="multipart/form-data">
        <div class="form-group">
            <label for="id_{{ form.name.html_name }}">{{ form.name.label }}</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Classroom name...">
            <b style="color: red">{{ form.name.errors }}</b>
        </div>
        <div class="form-group">
            <label for="id_{{ form.description.html_description }}">{{ form.description.label }}</label><br />
            <textarea cols="40" id="id_description" name="description" rows="10"></textarea>
            <b style="color: red">{{ form.description.errors }}</b>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="private"> Private?
                        <b style="color: red">{{ form.name.errors }}</b>
                    </label>
                </div>
            </div>
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Create Classroom</button>
    </form>
{% endblock %}

django_teams/templates/django_teams/team_detail.html
{% extends 'base.html' %}
{% load teams %}

{% block page-header %}
    <h1>{{ object }} <small>detailed information</small></h1>
    <p class="lead">{{ object.description }}</p>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Teachers</h3>
        </div>
        <div class="panel-body row">
            {% for owner in owners %}
                <div class="col-sm-6 col-md-2">
                    {% with object=owner %}
                    <a class="thumbnail">{% include owner|load_fragment_template %}</a>
                    {% endwith %}
                </div>
            {% endfor %}
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Classroom Members</h3>
        </div>
        <div class="panel-body row">
            {% for member in members %}
                <div class="col-sm-6 col-md-2">
                    {% with object=member %}
                    <a class="thumbnail">{% include member|load_fragment_template %}</a>
                    {% endwith %}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Approved Objects</h3>
        </div>
        <div class="panel-body row">
          {% for type in approved_objects_types %}
            {% for owned in type %}
              <div class="col-sm-6 col-md-2">
                  {% with object=owned %}
                  <a class="thumbnail">{% include object|load_fragment_template %}</a>
                  {% endwith %}
              </div>
            {% endfor %}
          {% endfor %}
        </div>
    </div>
{% endblock %}

django_teams/templates/django_teams/team_form.html
{% extends 'base.html' %}
{% load teams %}

{% block page-header %}
<h1>{{ object }} <small>admin page, <a href="{% url 'team-info-edit' pk=object.pk %}">change name</a></small></h1>
<p class="lead">{% if object.description %}{{ object.description }}{% endif %}</p>
{% endblock %}

{% block extra_head %}
    <style>
        .user-list select {
            display: none;
        }
        .selected {
            background-color: red;
        }
    </style>
{% endblock %}

{% block js %}
{{ block.super }}
    <script>
        var toggleSelected = function(selectId, objectId) {
            var selectObject = $('#'+selectId+'_'+objectId);
            selectObject.toggleClass('active');
            var values = $("#"+selectId).val();
            if(values == null || values == "")
                values = [];
            if(values.indexOf(objectId) > -1) {
                values.splice(values.indexOf(objectId), 1);
            } else {
                values.push(objectId);
            }

            $("#"+selectId).val(values);
        };
    </script>
{% endblock %}

{% block content %}

    <form class="form-horizontal" method="post" action="{% url 'team-edit' pk=object.pk %}">

    {% for group in form %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ group.prefix|capfirst }}</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-sm-1 control-label">Action</label>
                <div class="col-sm-11">
                    {{ group.action }}
                </div>
            </div>
            <div class="user-list row">
                {% for object in group.queryset %}
                    <div class="col-sm-6 col-md-2">
                    <a class="thumbnail" onclick="toggleSelected('{{ group.items.id_for_label }}', '{{ object.id }}')" id="{{ group.items.id_for_label }}_{{ object.id }}">{% include object|load_fragment_template %}</a>
                    </div>
                {% endfor %}
                {{ group.items }}
            </div>
            <!-- This get updated with JS when an object is clicked-->
            <button type="submit" class="btn btn-primary">Submit all changes</button>
        </div>
    </div>
    {% endfor %}

    {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit all changes</button>
    </form>
{% endblock %}

django_teams/templates/django_teams/team_list.html
{% extends 'base.html' %}
{% load teams %}

{% block page-header %}
{% endblock %}

{% block content %}
<div class="row" align="right">
    {% if user.is_authenticated %}
        <h4><a href="{% url 'team-create' %}">Create your own</a></h4>
    {% endif %}
</div>



<div class="row">
    <h2>Classrooms: </h2>
</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Classroom Name</th>
                <th>Classroom Description</th>
                <th>Classroom Owners</th>
                <th># of members</th>
                <th>Your status</th>
            </tr>
        </thead>
        {% for team in list %}
              {% include "django_teams/_table.html" %}
            
        {% endfor %}
    </table>
{% endblock %}

django_teams/templates/django_teams/teaminfo_form.html
{% extends 'base.html' %}

{% block page-header %}
<h1>Change classroom information</h1>
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" action="{% url 'team-info-edit' pk=object.pk %}" enctype="multipart/form-data">
        <div class="form-group">
            <label for="id_{{ form.name.html_name }}">{{ form.name.label }}</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Classroom name..." value="{{ object.name }}">
            <b style="color: red">{{ form.name.errors }}</b>
        </div>
        <div class="form-group">
            <label for="id_{{ form.description.html_description }}">{{ form.description.label }}</label><br />
            <textarea cols="40" id="id_description" name="description" rows="10">{{ object.description }}</textarea>
            <b style="color: red">{{ form.description.errors }}</b>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="private" value="{{ object.private }}"> Private?
                        <b style="color: red">{{ form.name.errors }}</b>
                    </label>
                </div>
            </div>
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Update Classroom</button>
    </form>
{% endblock %}

django_teams/templates/django_teams/teamstatus_form.html
{% extends 'base.html' %}

{% block page-header %}
<h1>Join Team <small>{{ team }}</small></h1>
{% endblock %}

{% block content %}

    <form class="form-horizontal" method="post" action="{% url 'teamstatus-create' team_pk=team.pk %}">
        <tr><th><label for="id_comment">Comment:</label></th><td><input id="id_comment" maxlength="255" name="comment" type="text" /></td></tr>

        <p>Your request will be reviewed by the teachers; {% for owner in team.owners %}
            {{ owner }}{% if not forloop.last %},{% endif %}{% endfor %}</p>

        <button type="submit" class="btn btn-primary">Request access</button>
        {% csrf_token %}
    </form>

{% endblock %}

django_teams/templates/django_teams/user_team_list.html
{% extends 'base.html' %}
{% load teams %}

{% block page-header %}
    <h1>Classrooms <small>in which you are the teacher</small></h1>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Classroom Name</th>
                <th>Classroom Description</th>
                <th>Classroom Owners</th>
                <th># of members</th>
                <th>Your status</th>
            </tr>
        </thead>
        {% for object in object_list %}
        <tr>
            <td><a href="{% url 'team-detail' pk=object.id %}">{{ object }}</a></td>
            <td>{% if object.description %}{{ object.description|truncatewords:15 }}{% endif %}</td>
            <td>
                {% for owner in object.owners %}
                    {% if forloop.last %}
                        {{ owner }}
                    {% else %}
                        {{ owner}},
                    {% endif %}
                {% endfor %}
            </td>
            <td>{{ object.member_count }}</td>
            <td>
                {% if user.is_authenticated %}
                    {% with ts=object|get_user_status:user %}
                        {% if ts == None %}
                            <a href="{% url 'teamstatus-create' team_pk=object.pk %}">Join</a>
                        {% elif ts.role == 1 %}
                            Pending approval
                        {% elif ts.role == 10 %}
                            Member
                        {% elif ts.role == 20 %}
                            Teacher (<a href="{% url 'team-edit' pk=object.pk %}">Admin</a>)
                        {% endif %}
                    {% endwith %}
                {% else %}
                    You're not logged in!
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}